### ISSUE TITLE
Deploying to Heroku?

### ISSUE THREAD

**Issue by michaelward82** [juliocesar/rack-pagespeed#33]
I get an error whenever I depoly my rails app to heroku (bamboo-mri-1.9.2 stack) with the rack-pagespeed gem included in my gem file.

I get the following returned:

```
Counting objects: 11, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (8/8), done.
Writing objects: 100% (8/8), 845 bytes, done.
Total 8 (delta 6), reused 0 (delta 0)

-----> Heroku receiving push
-----> Ruby/Rails app detected
-----> Configure Rails 3 to disable x-sendfile
       Installing rails3_disable_x_sendfile... done
-----> Configure Rails to log to stdout
       Installing rails_log_stdout... done
-----> Gemfile detected, running Bundler version 1.0.7
       Unresolved dependencies detected; Installing...
       Using --without development:test
       Fetching source index for http://rubygems.org/
       /usr/ruby1.9.2/lib/ruby/1.9.1/rubygems/specification.rb:289:in `load': uninitialized constant Syck::Syck (NameError)
        from /usr/ruby1.9.2/lib/ruby/1.9.1/rubygems/specification.rb:289:in `_load'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:119:in `load'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/rubygems/spec_fetcher.rb:119:in `fetch_spec'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/remote_specification.rb:47:in `_remote_specification'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/remote_specification.rb:53:in `method_missing'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:128:in `tsort_each_child'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/tsort.rb:203:in `each_strongly_connected_component_from'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:124:in `block in tsort_each_node'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:124:in `each'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:124:in `tsort_each_node'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/tsort.rb:148:in `tsort_each'
        from /usr/ruby1.9.2/lib/ruby/1.9.1/tsort.rb:135:in `tsort'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:107:in `sorted'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/spec_set.rb:12:in `each'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/installer.rb:44:in `run'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/installer.rb:8:in `install'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/cli.rb:225:in `install'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/vendor/thor/task.rb:22:in `run'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/vendor/thor/invocation.rb:118:in `invoke_task'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/vendor/thor.rb:246:in `dispatch'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/lib/bundler/vendor/thor/base.rb:389:in `start'
        from /usr/ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.0.7/bin/bundle:13:in `<top (required)>'
        from /usr/ruby1.9.2/bin/bundle:19:in `load'
        from /usr/ruby1.9.2/bin/bundle:19:in `<main>'
       FAILED: http://devcenter.heroku.com/articles/bundler
 !     Heroku push rejected, failed to install gems via Bundler

To git@heroku.com:confetti.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:confetti.git'
```

Gemfile

```
source 'http://rubygems.org'

gem 'sqlite3'

# REFINERY CMS ================================================================
# Anything you put in here will be overridden when the app gets updated.

gem 'refinerycms',              '~> 1.0.4'

group :development, :test do
  # To use refinerycms-testing, uncomment it (if it's commented out) and run 'bundle install'
  # Then, run 'rails generate refinerycms_testing' which will copy its support files.
  # Finally, run 'rake' to run the tests.
  # gem 'refinerycms-testing',    '~> 1.0.4'
end

# END REFINERY CMS ============================================================

# USER DEFINED
gem 'rack-pagespeed'
gem 'fog'
gem 'dalli'
gem 'newrelic_rpm'

group :development do
  gem "mongrel", "1.2.0.pre2"
end

# Specify additional Refinery CMS Engines here (all optional):
# gem 'refinerycms-inquiries',    '~> 1.0'
# gem "refinerycms-news",         '~> 1.2'
gem 'refinerycms-blog',         '~> 1.6'
# gem 'refinerycms-page-images',  '~> 1.0'

# Add i18n support (optional, you can remove this if you really want to).
gem 'refinerycms-i18n',         '~> 1.0.0'

# END USER DEFINED

```

Is this a known error?

**Comment by michaelward82** [comment]
I have fixed this using the edge version from git - but this has increased my slug size from 8MB to 27.1MB - so this is only a short term solution until a new version of the gem comes out.

**Comment by hone** [comment]
This is a bug in 1.1.1 and 1.1.0 versions of the gem pushed to rubygems. You can see the #YAML::Syck::DefaultKey:0xf06dbc8 under the development dependencies: https://rubygems.org/gems/rack-pagespeed/versions/1.1.1

Please use ruby 1.8.7 to push your gems up.
